trigger:
 - master

pool:
   vmImage: 'Ubuntu-16.04'
 
steps:
  - task: Ant@1
    inputs:
      buildFile: 'build.xml' 
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'

  - task: GitHubRelease@0
    inputs:
      gitHubConnection:  CommunityModules
      #repositoryName: '$(Build.Repository.Name)' 
      #action: 'create' # Options: create, edit, delete
      #target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
      tagSource: 'manual' # Required when action == Create# Options: auto, manual
      tag: '$(Build.BuildNumber)' # Required when action == Edit || Action == Delete || TagSource == Manual
      #title: # Optional
      #releaseNotesSource: 'file' # Optional. Options: file, input
      #releaseNotesFile: # Optional
      #releaseNotes: # Optional
      assets: 'dist/CommunityModules-*.jar' # Optional
      #assetUploadMode: 'delete' # Optional. Options: delete, replace
      #isDraft: false # Optional
      #isPreRelease: false # Optional
      #addChangeLog: true # Optional
